version: "3.7"

services:
  portfolio-manager:
    container_name: portfolio-manager
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    env_file: .env
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - $NODE_LOCAL_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    command: npm run dev
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
volumes:
  db:
